name: CI/CD pipeline with Dependabot

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Dependabot
      uses: dependabot/actions@v1
      with:
        github-token: ${{ secrets.MY_TOKEN }}
